# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - oldrel
  - release
  - devel

r_check_args: "--as-cran"

addons:
  apt:
    packages:
      - libgit2-dev

warnings_are_errors: false

after_success:
    - Rscript -e 'covr::codecov()'
    